apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-deployment
  labels:
    app: node-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: node-docker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-docker
    spec:
      containers:
      - name: node-docker
        image: ghcr.io/baabel/node-docker:latest
        ports:
        - containerPort: 8080
